--Bussiness Table -------

-- public.account_daily_balance definition

-- Drop table

-- DROP TABLE public.account_daily_balance;

CREATE TABLE public.account_daily_balance (
	account_id int8 NOT NULL,
	balance_date date NOT NULL,
	daily_total numeric(18, 2) DEFAULT 0 NULL,
	processed bool DEFAULT false NULL,
	CONSTRAINT account_daily_balance_pkey PRIMARY KEY (account_id, balance_date)
);


-- public.account_daily_balance foreign keys

ALTER TABLE public.account_daily_balance ADD CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	id bigserial NOT NULL,
	account_id int8 NOT NULL,
	amount numeric(18, 2) NOT NULL,
	status varchar(20) NOT NULL,
	transaction_date date NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_transactions_account ON public.transactions USING btree (account_id);
CREATE INDEX idx_transactions_date_status ON public.transactions USING btree (transaction_date, status);


-- public.transactions foreign keys

ALTER TABLE public.transactions ADD CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);

-- public.accounts definition

-- Drop table

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts (
	id bigserial NOT NULL,
	customer_name varchar(100) NULL,
	balance numeric(18, 2) DEFAULT 0 NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (id)
);


-- Autogenerated: do not edit this file

CREATE TABLE BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME VARCHAR(100) NOT NULL,
	PARAMETER_TYPE VARCHAR(100) NOT NULL,
	PARAMETER_VALUE VARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;


-- Séquences pour Spring Batch
CREATE SEQUENCE BATCH_JOB_SEQ START 1;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START 1;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START 1;
CREATE SEQUENCE BATCH_JOB_EXECUTION_CONTEXT_SEQ START 1;
CREATE SEQUENCE BATCH_STEP_EXECUTION_CONTEXT_SEQ START 1;


--CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
--CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
--CREATE SEQUENCE BATCH_JOB_INSTANCE_SEQ MAXVALUE 9223372036854775807 NO CYCLE;


ALTER TABLE BATCH_JOB_INSTANCE ALTER COLUMN JOB_INSTANCE_ID SET DEFAULT nextval('BATCH_JOB_SEQ');
ALTER TABLE BATCH_JOB_EXECUTION ALTER COLUMN JOB_EXECUTION_ID SET DEFAULT nextval('BATCH_JOB_EXECUTION_SEQ');
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN STEP_EXECUTION_ID SET DEFAULT nextval('BATCH_STEP_EXECUTION_SEQ');


-------Quelques Requetes SQL

SELECT
    a.id AS account_id,
    a.customer_name,
    a.balance AS current_balance,
    COALESCE(adb.balance_date, CURRENT_DATE - INTERVAL '1 day') AS balance_date,
    COALESCE(SUM(t.amount), 0) AS total_transactions,
    COALESCE(adb.daily_total, 0) AS daily_total,
    COALESCE(adb.processed, FALSE) AS daily_processed
FROM public.accounts a
LEFT JOIN public.account_daily_balance adb
    ON adb.account_id = a.id
   AND adb.balance_date = CURRENT_DATE - INTERVAL '1 day'
LEFT JOIN public.transactions t
    ON t.account_id = a.id
   AND t.transaction_date = CURRENT_DATE - INTERVAL '1 day'
   AND t.status = 'VALIDATED'
GROUP BY
    a.id,
    a.customer_name,
    a.balance,
    adb.balance_date,
    adb.daily_total,
    adb.processed
ORDER BY a.id;



SELECT
    a.id AS account_id,
    a.customer_name,
    a.balance AS current_balance,
    COALESCE(adb.balance_date, CURRENT_DATE - INTERVAL '1 day') AS balance_date,
    COALESCE(SUM(t.amount), 0) AS total_transactions,
    COALESCE(adb.daily_total, 0) AS daily_total,
    COALESCE(adb.processed, FALSE) AS daily_processed
FROM public.accounts a
LEFT JOIN public.account_daily_balance adb
    ON adb.account_id = a.id
   AND adb.balance_date = CURRENT_DATE - INTERVAL '1 day'
LEFT JOIN public.transactions t
    ON t.account_id = a.id
   AND t.transaction_date = CURRENT_DATE - INTERVAL '1 day'
   AND t.status = 'VALIDATED'
WHERE COALESCE(adb.processed, FALSE) = FALSE
GROUP BY
    a.id,
    a.customer_name,
    a.balance,
    adb.balance_date,
    adb.daily_total,
    adb.processed
ORDER BY a.id;
